/**
 * Playwright Storage Server Utilities.
 *
 * Resolves shared screenshot directories and safely reads screenshot files
 * generated by Playwright MCP containers.
 */

import "server-only";

import * as fs from "node:fs";
import * as path from "node:path";
import { logger } from "@/lib/observability/logger";

/**
 * Resolve the Playwright output directory on the host/container.
 * Defaults to <cwd>/.cache/playwright, overridable via PLAYWRIGHT_OUTPUT_DIR.
 */
export function resolvePlaywrightOutputDir(): string {
  const envPath = process.env.PLAYWRIGHT_OUTPUT_DIR;
  if (envPath && envPath.trim().length > 0) {
    return path.resolve(envPath.trim());
  }
  return path.join(process.cwd(), ".cache", "playwright");
}

export interface PlaywrightScreenshotFile {
  buffer: Buffer;
  mimeType: string;
  filename: string;
}

const MIME_MAP: Record<string, string> = {
  ".png": "image/png",
  ".webp": "image/webp",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".svg": "image/svg+xml",
};

/**
 * Clean up raw file path from Playwright tool response.
 * Strips leading relative tokens (./, .playwright-mcp/, /app/.output/, etc.).
 */
export function sanitizePlaywrightFilename(raw: string): string {
  let cleaned = raw.trim();
  // Strip quotes if present
  cleaned = cleaned.replace(/^['"]|['"]$/g, "");
  // Replace Windows backslashes with forward slashes for uniform parsing
  cleaned = cleaned.replace(/\\/g, "/");

  // Remove common container/relative path prefixes
  cleaned = cleaned.replace(/^(\.\/|\/app\/\.output\/|\.playwright-mcp\/)/, "");

  // Return base filename to prevent path traversal
  return path.basename(cleaned);
}

/**
 * Extract screenshot filename from Playwright MCP text output.
 */
export function extractFilenameFromScreenshotText(text: string): string | null {
  if (!text || typeof text !== "string") return null;
  const mdMatch = text.match(/\[(?:[^\]]*screenshot[^\]]*)\]\(([^)]+)\)/i);
  const codeMatch = text.match(/path:\s*['"]([^'"]+)['"]/i);
  const rawPath = mdMatch?.[1] || codeMatch?.[1];
  if (!rawPath) return null;
  const filename = sanitizePlaywrightFilename(rawPath);
  return filename && filename !== "." && filename !== ".." ? filename : null;
}

/**
 * Read a screenshot file from the shared Playwright output directory.
 * Includes security checks against directory traversal and extension probing.
 */
export async function readPlaywrightScreenshot(
  rawFilename: string,
): Promise<PlaywrightScreenshotFile | null> {
  if (!rawFilename || typeof rawFilename !== "string") {
    return null;
  }

  const filename = sanitizePlaywrightFilename(rawFilename);
  if (!filename || filename === "." || filename === "..") {
    return null;
  }

  const outputDir = resolvePlaywrightOutputDir();

  // Candidate paths to check (handling both direct root and .playwright-mcp subdirectories)
  const ext = path.extname(filename).toLowerCase();
  const candidates: string[] = [
    path.join(outputDir, filename),
    path.join(outputDir, ".playwright-mcp", filename),
  ];

  if (!ext) {
    candidates.push(
      path.join(outputDir, `${filename}.png`),
      path.join(outputDir, `${filename}.webp`),
      path.join(outputDir, `${filename}.jpg`),
      path.join(outputDir, `${filename}.jpeg`),
      path.join(outputDir, ".playwright-mcp", `${filename}.png`),
      path.join(outputDir, ".playwright-mcp", `${filename}.webp`),
    );
  }

  let foundPath: string | null = null;
  for (const candidate of candidates) {
    // SECURITY: Ensure candidate path is strictly within outputDir (prevent traversal)
    const relative = path.relative(outputDir, candidate);
    if (relative.startsWith("..") || path.isAbsolute(relative)) {
      continue;
    }

    try {
      if (fs.existsSync(candidate) && fs.statSync(candidate).isFile()) {
        foundPath = candidate;
        break;
      }
    } catch {
      // Ignore stat errors
    }
  }

  if (!foundPath) {
    logger.warn(
      {
        component: "playwright-storage",
        rawFilename,
        sanitizedFilename: filename,
        outputDir,
      },
      "Screenshot file not found in Playwright output directory. Please verify that '.cache/playwright' is mounted in docker-compose.yaml.",
    );
    return null;
  }

  try {
    const buffer = await fs.promises.readFile(foundPath);
    const foundExt = path.extname(foundPath).toLowerCase();
    const mimeType = MIME_MAP[foundExt] || "image/png";

    return {
      buffer,
      mimeType,
      filename: path.basename(foundPath),
    };
  } catch (err) {
    logger.error(
      {
        component: "playwright-storage",
        foundPath,
        err: err instanceof Error ? err.message : String(err),
      },
      "Failed to read screenshot file from disk",
    );
    return null;
  }
}
