/**
 * Pure helpers for `scripts/collect-skill-deps.ts`. Extracted so the script and runtime can share the same logic.
 */

/**
 * Always-present packages baked into the sandbox image regardless of
 * skill declarations. These back the D36 main data pipeline:
 *   - `duckdb`  — runs SQL inside `extract_dataset_by_sql` against
 *                 cached Parquet files.
 *   - `pandas`  — the canonical DataFrame surface code nodes use.
 *   - `numpy`   — pandas' implicit dep + the basic numeric runtime.
 *   - `pyarrow` — the parquet engine `pd.read_parquet` resolves; D36
 *                 materializes every dataset as Parquet so this is
 *                 required for the SQL → code happy path. Without it
 *                 `pd.read_parquet` raises an ImportError before any
 *                 user code can run.
 *
 * Note: skill authors MAY still re-declare these in their SKILL.md
 * frontmatter; `mergeDeps` dedupes inside `core` and surfaces version
 * conflicts to the operator.
 */
export const CORE_PACKAGES: readonly string[] = [
  "duckdb",
  "pandas",
  "numpy",
  "pyarrow",
];

/** A single dependency declaration with provenance for diagnostics. */
export interface DeclaredDep {
  /** Full pip spec as written by the author, e.g. `"scikit-learn>=1.3"`. */
  raw: string;
  /** Package name without spec, lowercase. Used as the conflict key. */
  packageName: string;
  /** Source for diagnostics: `skills/<name>/SKILL.md`, or `<core>`. */
  source: string;
}

/** Per-skill aggregation, before merging across skills. */
export interface SkillDeps {
  skillName: string;
  deps: DeclaredDep[];
}

export interface MergedDeps {
  core: DeclaredDep[];
  bySkill: Map<string, DeclaredDep[]>;
}

/**
 * Parse a pip requirement spec to extract the lowercase package name.
 * Strips PEP 440 version specifiers (`==`, `>=`, `<`, `~=`, `!=`) and
 * extras (`pkg[extra]`). Strict enough for conflict detection; not a
 * full PEP 508 parser.
 *
 * @throws when the spec cannot yield a recognisable package token.
 */
export function packageNameOf(spec: string): string {
  // First split on extras: pkg[ext1,ext2]==1.0 -> "pkg"
  const noExtras: string = spec.split("[")[0];
  const match: RegExpMatchArray | null = noExtras.match(/^([A-Za-z0-9_.-]+)/);
  if (!match) {
    throw new Error(
      `Could not extract package name from dependency spec: ${spec}`,
    );
  }
  return match[1].toLowerCase();
}

/** Build a {@link DeclaredDep} from a raw spec + source path. */
export function declaredDep(raw: string, source: string): DeclaredDep {
  return {
    raw,
    packageName: packageNameOf(raw),
    source,
  };
}

/**
 * Merge core + per-skill declarations into the final pinned list,
 * detecting package-level conflicts.
 *
 * Conflict policy: if two declarations share the same lowercase
 * package name but differ in raw spec string, this throws with all
 * conflicts enumerated. We do NOT auto-pick a "winner" — that
 * guesses author intent.
 *
 * Same raw spec string in two skills is silently deduped.
 */
export function mergeDeps(perSkill: SkillDeps[]): MergedDeps {
  const firstSeen: Map<string, DeclaredDep> = new Map();
  const conflicts: string[] = [];

  function record(d: DeclaredDep): void {
    const existing: DeclaredDep | undefined = firstSeen.get(d.packageName);
    if (!existing) {
      firstSeen.set(d.packageName, d);
      return;
    }
    if (existing.raw !== d.raw) {
      conflicts.push(
        `  ${d.packageName}: ${existing.source} declares "${existing.raw}" vs ${d.source} declares "${d.raw}"`,
      );
    }
  }

  const core: DeclaredDep[] = CORE_PACKAGES.map((pkg) => declaredDep(pkg, "<core>"));
  for (const c of core) record(c);

  const bySkill: Map<string, DeclaredDep[]> = new Map();
  for (const sd of perSkill) {
    if (sd.deps.length === 0) continue;
    bySkill.set(sd.skillName, sd.deps);
    for (const d of sd.deps) record(d);
  }

  if (conflicts.length > 0) {
    throw new Error(
      `Dependency conflict between skills:\n${conflicts.join("\n")}\n` +
        `Resolve by aligning the version specs in the source SKILL.md files.`,
    );
  }
  return { core, bySkill };
}

/**
 * Render the final requirements.txt content, with grouping comments
 * and stable sort across skill names. Includes a "do not edit"
 * banner so on-disk drift is obviously author-introduced.
 */
export function renderRequirements(merged: MergedDeps): string {
  const lines: string[] = [
    "# AUTO-GENERATED by `pnpm sandbox:build` from skills/*/SKILL.md.",
    "# DO NOT EDIT BY HAND — regenerate via `pnpm sandbox:build`.",
    "# CI enforces drift via `pnpm sandbox:check`.",
    "# @see docs/skills.md §9.x",
    "",
    "# === core ===",
  ];
  // Dedupe inside core (in case author shadows a core pkg with the same spec).
  const written: Set<string> = new Set();
  for (const d of merged.core) {
    if (written.has(d.packageName)) continue;
    written.add(d.packageName);
    lines.push(d.raw);
  }

  // Sort skill groups for stable output regardless of fs order.
  const skillNames: string[] = [...merged.bySkill.keys()].sort();
  for (const skillName of skillNames) {
    const deps: DeclaredDep[] = merged.bySkill.get(skillName)!;
    const fresh: DeclaredDep[] = deps.filter(
      (d) => !written.has(d.packageName),
    );
    if (fresh.length === 0) continue;
    lines.push("", `# === from skills/${skillName} ===`);
    for (const d of fresh) {
      written.add(d.packageName);
      lines.push(d.raw);
    }
  }
  // Trailing newline so POSIX tools are happy.
  lines.push("");
  return lines.join("\n");
}
